# Generated by Django 3.1.4 on 2023-02-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20230211_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='no email provided', max_length=254),
        ),
    ]
